# Site settings
title: Rino Bellocco
email: rino.bellocco@unimib.it
description: >
    © Rino Bellocco. Powered by <a href=http://jekyllrb.com/>jekyll</a>. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: Rinosky
github_username:  rinobellocco

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"